CREATE TABLE "MFT110"."CLAIMS" (
		"CLAIMNUMBER" INTEGER NOT NULL, 
		"POLICYNUMBER" INTEGER WITH DEFAULT NULL, 
		"CLAIMDATE" DATE WITH DEFAULT NULL, 
		"PAID" INTEGER WITH DEFAULT NULL, 
		"VALUE" INTEGER WITH DEFAULT NULL, 
		"CAUSE" VARCHAR(255) FOR SBCS DATA WITH DEFAULT NULL, 
		"OBSERVATIONS" VARCHAR(255) FOR SBCS DATA WITH DEFAULT NULL
	)
	IN "TESTDB"."TESTTS9"
	AUDIT NONE
	DATA CAPTURE CHANGES 
	CCSID EBCDIC;

CREATE UNIQUE INDEX "MFT110"."Claims_PK"
	ON "MFT110"."CLAIMS"
	("CLAIMNUMBER");

ALTER TABLE "MFT110"."CLAIMS" ADD CONSTRAINT "Claims_PK" PRIMARY KEY
	("CLAIMNUMBER");

